.TH "libjpegtest" 1 "Nov 2010" "SH JPEG" "Linux-SH Multimedia"

.SH NAME
libjpegtest \- Encode/decode JPEG images using the SH-Mobile JPU through the libjpeg interface

.SH SYNOPSIS

.B \fBlibjpegtest\fR \fI[OPTIONS]\fR \fI<jpegfile>\fR \fI[<output>]\fR

.SH DESCRPITOIN
.B libjpegtest
Decodeds given JPEG file, and then re-encode. Run \fBlibjpegtest --help\fR for more details.

.SH AUTHORS
libjpegtest was written by Damian Hobson-Garcia

Please report bugs to <dhobsong@igel.co.jp>
